# Generated by Django 2.2.4 on 2019-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchfile_name', models.CharField(max_length=250, verbose_name='Batch File Name')),
                ('file_path', models.FileField(upload_to='upload/%Y/%m/%d', verbose_name='Files')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
