# Generated by Django 2.2.4 on 2019-08-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload',
            table='input_master',
        ),
    ]
