# Generated by Django 2.2.4 on 2019-08-19 10:33

from django.db import migrations, models
import upload.validators


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190809_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='download_path',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to='upload/%Y/%m/%d', validators=[upload.validators.validate_file_extension], verbose_name='Files'),
        ),
    ]
